import { Inter } from 'next/font/google';
import Head from 'next/head';
import Link from 'next/link';
import { useState } from 'react';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  // console.log(process.env.NEXT_PUBLIC_WORDLINK_API_KEY);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div
        style={{
          display: 'flex',
        }}>
        <Link href='/canvas'>
          <button style={{ display: 'flex', width: 200, height: 60, alignItems: 'center', justifyContent: 'center' }}>CANVAS</button>
        </Link>
        <Link href='/games'>
          <button style={{ display: 'flex', width: 200, height: 60, alignItems: 'center', justifyContent: 'center' }}>GAMES</button>
        </Link>
        <Link href='/etc'>
          <button style={{ display: 'flex', width: 200, height: 60, alignItems: 'center', justifyContent: 'center' }}>ETC</button>
        </Link>
        <AnimationButton />
      </div>
    </>
  );
}

/**
 * https://mfisher-apollonas.com/
 * 메인 네비게이션 버튼 클론코딩
 */
const AnimationButton = () => {
  const [isHover, setIsHover] = useState(true);
  const onMouseEnter = () => {
    setIsHover(true);
  };
  const onMouseLeave = () => {
    setIsHover(false);
  };

  return (
    <div
      onMouseEnter={onMouseEnter}
      onMouseLeave={onMouseLeave}
      className='Welcome_buttonWrap'
      style={{
        overflow: 'hidden',
        width: 200,
        height: 45,
        position: 'relative',
        borderRadius: 50,
        cursor: 'pointer',
      }}>
      <button className='Welcome_button' style={{ width: '100%', height: '100%', border: 'none' }}>
        <div
          className='Welcome_originalBg'
          style={{
            backgroundColor: '#f4efe9',
            borderRadius: '100%',
            display: 'block',
            height: '200%',
            left: '-50%',
            position: 'absolute',
            top: ' -40%',
            width: '200%',
            transition: 'transform .6s',
            transform: 'translate3d(0,0,0)',
          }}
        />
        <div
          className='Welcome_hiddenBg'
          style={{
            backgroundColor: '#544c3f',
            borderRadius: '100%',
            display: 'block',
            height: '200%',
            left: '-50%',
            position: 'absolute',
            top: ' -40%',
            width: '200%',
            transition: 'transform .6s',
            transform: isHover ? 'translate3d(0,15%,0)' : 'translate3d(0,100%,0)',
          }}
        />
        <div className='Welcome_textWrap'>
          <div className='Welcome_innerText' style={{ transform: 'translateY(0)', transition: 'transform 1s cubic-bezier(.19,.39,0,.99) 2.1s' }}>
            <div className='Welcome_text' style={{ transition: 'transform .6s cubic-bezier(.36,.28,0,.99)' }}>
              Enter Experience
            </div>
            <div
              className='Welcome_hiddenText'
              style={{
                transform: 'translate3d(0,400%,1px) rotate(30deg)',
                transition: 'transform .6s cubic-bezier(.36,.28,0,.99)',
                position: 'absolute',
              }}>
              Enter Experience
            </div>
          </div>
        </div>
      </button>
    </div>
  );
};
