import Map from "@/components/Map";
import {
  atomBubblePositions,
  atomNumPerLine,
  atomPlayerPosition,
} from "@/recoil/atoms";
import { Inter } from "next/font/google";
import Head from "next/head";
import { useEffect } from "react";
import { useRecoilState, useRecoilValue } from "recoil";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [playerPosition, setPlayerPosition] =
    useRecoilState(atomPlayerPosition);
  const numPerLine = useRecoilValue(atomNumPerLine);
  const [bubblePositions, setBubblePositions] =
    useRecoilState(atomBubblePositions);

  useEffect(() => {
    const handleKeyboardInput = (e: KeyboardEvent) => {
      // console.log(e.code);
      if (e.code === "ArrowUp") {
        if (playerPosition.x === 0) return;
        setPlayerPosition((cur) => {
          return { x: cur.x - 1, y: cur.y };
        });
      }
      if (e.code === "ArrowRight") {
        if (playerPosition.y === numPerLine - 1) return;
        setPlayerPosition((cur) => {
          return { x: cur.x, y: cur.y + 1 };
        });
      }
      if (e.code === "ArrowDown") {
        if (playerPosition.x === numPerLine - 1) return;
        setPlayerPosition((cur) => {
          return { x: cur.x + 1, y: cur.y };
        });
      }
      if (e.code === "ArrowLeft") {
        if (playerPosition.y === 0) return;
        setPlayerPosition((cur) => {
          return { x: cur.x, y: cur.y - 1 };
        });
      }
      if (e.code === "Space") {
        if (
          bubblePositions.filter(
            (item) => item.x === playerPosition.x && item.y === playerPosition.y
          ).length !== 0
        )
          return;
        setBubblePositions((cur) => [
          ...cur,
          { x: playerPosition.x, y: playerPosition.y },
        ]);
      }
    };

    window.addEventListener("keydown", handleKeyboardInput);

    return () => window.removeEventListener("keydown", handleKeyboardInput);
  }, [playerPosition, numPerLine]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Map />
      </div>
    </>
  );
}
