import GoogleMap from '@/component/geolocation/map';
import Marker from '@/component/geolocation/marker';
import {Inter} from 'next/font/google';
import Head from 'next/head';
import {useState} from 'react';

const inter = Inter({subsets: ['latin']});

export interface MarkerProps {
  position: {lat: number; lng: number};
  title: string;
}

export default function Home() {
  const [map, setMap] = useState<google.maps.Map | null>(null);
  const locations: Array<MarkerProps> = [{position: {lat: 37.50098, lng: 127.03623}, title: '패스트파이브 역삼 3호점'}];

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{height: '100vh', width: '100%'}}>
        <div id="map" style={{width: '100%', height: '100vh'}}>
          <GoogleMap map={map} setMap={setMap} />
          {map ? locations.map((item, idx) => <Marker key={idx} position={item.position} map={map} title={item.title} onClick={console.log} />) : null}
        </div>
      </div>
    </>
  );
}
